---
unclassified:
  artifactManager:
    artifactManagerFactories:
      - jclouds:
          provider: s3
aws:
  awsCredentials:
    # FIXME: not a sensible default for everyone
    region: "us-east-1"
  s3:
    # TODO: create through CloudFormation
    container: "${ARTIFACT_MANAGER_S3_BUCKET_NAME}"
    prefix: "jenkins_data/"
